# Generated by Django 4.2.6 on 2023-11-03 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_alter_tarefa_descricao_alter_tarefa_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='titulo',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(25)]),
        ),
    ]
