# Generated by Django 4.2.6 on 2023-11-10 23:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tarefas.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tarefas', '0005_alter_tarefa_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='data',
            field=models.DateField(validators=[tarefas.models.validate_data]),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Certifique-se de que a descrição tenha no mínimo 3 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='titulo',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Certifique-se de que o título tenha no mínimo 3 caracteres.')]),
        ),
    ]
